config/routes.rb
GitosisAdministration::Application.routes.draw do
  resources :key_pairs

  resources :groups

  resources :repositories

  devise_for :users

  resources :users

root :to => "repositories#index"
end

app/models/repository.rb
class Repository < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :groups
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.xml
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.xml
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.xml
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.xml
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to(@repository, :notice => 'Repository was successfully created.') }
        format.xml  { render :xml => @repository, :status => :created, :location => @repository }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.xml
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to(@repository, :notice => 'Repository was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.xml
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :visibility %><br />
    <%= f.text_field :visibility %>
  </div>
  <div class="field">
    <%= f.label :daemon %><br />
    <%= f.check_box :daemon %>
  </div>
  <div class="field">
    <%= f.label :gitweb %><br />
    <%= f.check_box :gitweb %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>


<% @repositories.each do |repository| %>

	<div class="repository-list">
		<div class="repository-list-owner"><%= repository.owner %>/ </div>
		<div class="repository-list-name">  <%= repository.name %></div>
		<div class="repository-list-info">Users: 100 | Groups: 100 Visibility: Members | Daemon: <%= repository.daemon %> | Gitweb: <%= repository.gitweb %></div>
		<div class="repository-list-description"><%= repository.description %></div>
		<div class="repository-list-links"><%= link_to 'Show', repository %> | <%= link_to 'Edit', edit_repository_path(repository) %> | <%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></div>
	</div>
	<hr>
<% end %>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<p>
  <b>Description:</b>
  <%= @repository.description %>
</p>

<p>
  <b>Visibility:</b>
  <%= @repository.visibility %>
</p>

<p>
  <b>Daemon:</b>
  <%= @repository.daemon %>
</p>

<p>
  <b>Gitweb:</b>
  <%= @repository.gitweb %>
</p>

<p>
  <b>Owner:</b>
  <%= @repository.owner %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>