config/routes.rb
GitosisAdministration::Application.routes.draw do
  resources :key_pairs

  resources :groups

  resources :repositories

  devise_for :users

  resources :users

root :to => "repositories#index"
end

app/models/key_pair.rb
class KeyPair < ActiveRecord::Base
	belongs_to :user
end

app/controllers/key_pairs_controller.rb
class KeyPairsController < ApplicationController
  # GET /key_pairs
  # GET /key_pairs.xml
  def index
    @key_pairs = KeyPair.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @key_pairs }
    end
  end

  # GET /key_pairs/1
  # GET /key_pairs/1.xml
  def show
    @key_pair = KeyPair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @key_pair }
    end
  end

  # GET /key_pairs/new
  # GET /key_pairs/new.xml
  def new
    @key_pair = KeyPair.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @key_pair }
    end
  end

  # GET /key_pairs/1/edit
  def edit
    @key_pair = KeyPair.find(params[:id])
  end

  # POST /key_pairs
  # POST /key_pairs.xml
  def create
    @key_pair = KeyPair.new(params[:key_pair])

    respond_to do |format|
      if @key_pair.save
        format.html { redirect_to(@key_pair, :notice => 'Key pair was successfully created.') }
        format.xml  { render :xml => @key_pair, :status => :created, :location => @key_pair }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @key_pair.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /key_pairs/1
  # PUT /key_pairs/1.xml
  def update
    @key_pair = KeyPair.find(params[:id])

    respond_to do |format|
      if @key_pair.update_attributes(params[:key_pair])
        format.html { redirect_to(@key_pair, :notice => 'Key pair was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @key_pair.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /key_pairs/1
  # DELETE /key_pairs/1.xml
  def destroy
    @key_pair = KeyPair.find(params[:id])
    @key_pair.destroy

    respond_to do |format|
      format.html { redirect_to(key_pairs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/key_pairs_helper.rb
module KeyPairsHelper
end

app/views/key_pairs/_form.html.erb
<%= form_for(@key_pair) do |f| %>
  <% if @key_pair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_pair.errors.count, "error") %> prohibited this key_pair from being saved:</h2>

      <ul>
      <% @key_pair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :key_type %><br />
    <%= f.text_field :key_type %>
  </div>
  <div class="field">
    <%= f.label :public_key %><br />
    <%= f.text_area :public_key %>
  </div>
  <div class="field">
    <%= f.label :private_key %><br />
    <%= f.text_area :private_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/key_pairs/edit.html.erb
<h1>Editing key_pair</h1>

<%= render 'form' %>

<%= link_to 'Show', @key_pair %> |
<%= link_to 'Back', key_pairs_path %>

app/views/key_pairs/index.html.erb
<h1>Listing key_pairs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Key type</th>
    <th>Public key</th>
    <th>Private key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @key_pairs.each do |key_pair| %>
  <tr>
    <td><%= key_pair.user_id %></td>
    <td><%= key_pair.key_type %></td>
    <td><%= key_pair.public_key %></td>
    <td><%= key_pair.private_key %></td>
    <td><%= link_to 'Show', key_pair %></td>
    <td><%= link_to 'Edit', edit_key_pair_path(key_pair) %></td>
    <td><%= link_to 'Destroy', key_pair, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Key pair', new_key_pair_path %>

app/views/key_pairs/new.html.erb
<h1>New key_pair</h1>

<%= render 'form' %>

<%= link_to 'Back', key_pairs_path %>

app/views/key_pairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @key_pair.user_id %>
</p>

<p>
  <b>Key type:</b>
  <%= @key_pair.key_type %>
</p>

<p>
  <b>Public key:</b>
  <%= @key_pair.public_key %>
</p>

<p>
  <b>Private key:</b>
  <%= @key_pair.private_key %>
</p>


<%= link_to 'Edit', edit_key_pair_path(@key_pair) %> |
<%= link_to 'Back', key_pairs_path %>